apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akstech-sg-tls
  namespace: crm-dev
spec:
  secretName: akstech-sg
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: akstech.sg
  dnsNames:
    - akstech.sg
    - www.akstech.sg
