apiVersion: v1
kind: PersistentVolume
metadata:
  name: crm-backbone-db-volume
  namespace: crm-dev
  labels:
    type: local
    app: postgres-db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: "/mnt/data"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crm-backbone-db-storage
  namespace: crm-dev
  labels:
    app: postgres-db
spec:
  storageClassName: slow
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
