
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-backbone-db-deployment
  namespace: crm-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      # volumes:
      # - name: crm-db-storage
      #   persistentVolumeClaim:
      #     claimName: crm-backbone-db-storage
      containers:
      - name: crm-backbone-db
        image: karthiksgd/crm-db:v1.0.7
        # command:
        # - /usr/bin/su - postgres
        # - /bin/bash
        # - -R
        # - "1000"
        # - /var/lib/postgresql/data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # env:
        #     - name : POSTGRES_PASSWORD
        #       value: postgres
        envFrom:
        - configMapRef: 
            name: crm-db-config
        ports:
        - containerPort: 5432
        # volumeMounts:
        # - name: crm-db-storage
        #   mountPath: /var/lib/postgresql/data
        #   subPath: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: crm-backbone-db-service
  namespace: crm-dev
spec:
  type: ClusterIP
  selector:
    app: postgres-db
  ports:
  - port: 5432
    targetPort: 5432



